# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- task: docker@0
  inputs:
    Action: Build an image
    ContainerRegistryType: Azure Container Registry
    AzureSubscriptionEndpoint: Visual Studio Professional
    ImageName: $(Build.Repository.Name):$(Build.BuildId)
    AzureContainerRegistry: startacr.azurecr.io
    
- task: docker@0
  inputs:
    Action: Push an image
    ContainerRegistryType: Azure Container Registry
    AzureSubscriptionEndpoint: Visual Studio Professional
    ImageName: $(Build.Repository.Name):$(Build.BuildId)
    AzureContainerRegistry: startacr.azurecr.io
