# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- script: |
    dotnet restore
    dotnet build
    
- task: docker@0
  inputs:
    Action: Build an image
    ContainerRegistryType: Azure Container Registry
    AzureSubscriptionEndpoint: "d4faa0f5-d923-40da-a956-18d8b0cefe00"
    ImageName: $(Build.Repository.Name):$(Build.BuildId)
    AzureContainerRegistry: startacr.azurecr.io

- task: dotNetCoreCli@1
  inputs:
    Command: publish
    Arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
    ZipAfterPublish: true

#- task: archiveFiles@1
#  inputs:
#    rootFolder: $(Build.ArtifactStagingDirectory)
#    archiveFile: $(Build.BuildId).zip

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
