# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- task: docker@0
  inputs:
    Action: Build an image
    ContainerRegistryType: Azure Container Registry
    AzureSubscriptionEndpoint: Azure-VS-Professional
    ImageName: $(Build.Repository.Name):$(Build.BuildId)
    AzureContainerRegistry: '{"loginServer":"startacr.azurecr.io", "id" : "/subscriptions/d4faa0f5-d923-40da-a956-18d8b0cefe00/resourceGroups/start-rg/providers/Microsoft.ContainerRegistry/registries/startacr"}'

- task: docker@0
  inputs:
    Action: Push an image
    ContainerRegistryType: Azure Container Registry
    AzureSubscriptionEndpoint: Azure-VS-Professional
    ImageName: $(Build.Repository.Name):$(Build.BuildId)
    AzureContainerRegistry: '{"loginServer":"startacr.azurecr.io", "id" : "/subscriptions/d4faa0f5-d923-40da-a956-18d8b0cefe00/resourceGroups/start-rg/providers/Microsoft.ContainerRegistry/registries/startacr"}'
